"""Translate StoryMapJS JSON files from English to Spanish and Portuguese.

Standalone post-processing script that reads the English StoryMap JSON files
generated by build_storymaps.py and produces translated versions using the
Google Cloud Translation API.

Translatable content:
- Title/overview slide: headline, subtitle, template phrases
- Language slides: labels ("Indigenous name:", "AILLA holdings:", etc.),
  staff-authored descriptions, and template text
- Summary slide: headline, template phrases

Preserved (not translated):
- Language names (kept in original form, including indigenous names)
- ISO 639-3 codes
- URLs and AILLA links
- Numbers, dates, coordinates
- HTML structure/tags

Usage:
    # Translate both maps to both languages
    uv run scripts/translate_storymaps.py

    # Translate only Mayan map
    uv run scripts/translate_storymaps.py --family mayan

    # Translate to Spanish only
    uv run scripts/translate_storymaps.py --lang es

    # Dry run (show what would be translated, no API calls)
    uv run scripts/translate_storymaps.py --dry-run

Requires:
    - google-cloud-translate package
    - GOOGLE_APPLICATION_CREDENTIALS env var pointing to a service account key,
      OR application default credentials (gcloud auth application-default login)

Output:
    data/mayan_storymap_es.json, data/mayan_storymap_pt.json
    data/quechua_storymap_es.json, data/quechua_storymap_pt.json
    + corresponding preview HTML files
"""

import argparse
import copy
import json
import re
import sys
from pathlib import Path
from typing import Any

from google.cloud import translate_v2 as translate


# --- Configuration ---

# Source JSON files (English, produced by build_storymaps.py)
SOURCE_FILES = {
    "mayan": "mayan_storymap.json",
    "quechua": "quechua_storymap.json",
}

TARGET_LANGUAGES = {
    "es": "Spanish",
    "pt": "Portuguese",
}

# Labels that appear as <em>Label:</em> in slide HTML.
# These are translated via a lookup dict first (more reliable than API for
# short phrases), with the API as a fallback.
LABEL_TRANSLATIONS = {
    "es": {
        "Indigenous name:": "Nombre indígena:",
        "Also known as:": "También conocido como:",
        "Countries:": "Países:",
        "AILLA holdings:": "Fondos de AILLA:",
        "Dates created:": "Fechas de creación:",
        "Dates deposited:": "Fechas de depósito:",
        "ISO 639-3:": "ISO 639-3:",
        "View in AILLA": "Ver en AILLA",
        "Visit AILLA": "Visitar AILLA",
        "Explore all AILLA collections": "Explorar todas las colecciones de AILLA",
        "Additional Languages": "Lenguas adicionales",
    },
    "pt": {
        "Indigenous name:": "Nome indígena:",
        "Also known as:": "Também conhecido como:",
        "Countries:": "Países:",
        "AILLA holdings:": "Acervo do AILLA:",
        "Dates created:": "Datas de criação:",
        "Dates deposited:": "Datas de depósito:",
        "ISO 639-3:": "ISO 639-3:",
        "View in AILLA": "Ver no AILLA",
        "Visit AILLA": "Visitar o AILLA",
        "Explore all AILLA collections": "Explorar todas as coleções do AILLA",
        "Additional Languages": "Línguas adicionais",
    },
}

# Template phrases that appear in title/summary slides.
# Applied longest-first to avoid partial matches. Short words like "item"
# use regex word boundaries to prevent matching inside URLs or other words.
TEMPLATE_TRANSLATIONS = {
    "es": {
        # Full sentences (applied first due to length-sorting)
        "Slides are ordered chronologically by the earliest recording date in AILLA's holdings.":
            "Las diapositivas están ordenadas cronológicamente por la fecha de grabación más antigua en los fondos de AILLA.",
        "As AILLA's collections grow, these languages may be featured in future updates to this map.":
            "A medida que las colecciones de AILLA crezcan, estas lenguas podrán aparecer en futuras actualizaciones de este mapa.",
        "in the Archive of the Indigenous Languages of Latin America (AILLA) at the University of Texas at Austin.":
            "en el Archivo de las Lenguas Indígenas de América Latina (AILLA) de la Universidad de Texas en Austin.",
        "A chronological journey through the documentation of": "Un recorrido cronológico a través de la documentación de",
        # Title-slide headlines
        "Mayan Languages in the AILLA Archive": "Lenguas mayas en el archivo AILLA",
        "Quechua Languages in the AILLA Archive": "Lenguas quechuas en el archivo AILLA",
        # Multi-word phrases (safe for plain string replacement)
        "Mayan languages": "las lenguas mayas",
        "Quechua languages": "las lenguas quechuas",
        "items in AILLA's current holdings.": "elementos en los fondos actuales de AILLA.",
        "are listed in the closing summary.": "se enumeran en el resumen final.",
        "is listed in the closing summary.": "se enumera en el resumen final.",
        "with detailed slides": "con diapositivas detalladas",
        "detailed slides": "diapositivas detalladas",
        "This map features": "Este mapa presenta",
        "have fewer than": "tienen menos de",
        "An additional": "Además,",
        "Mayan family": "familia maya",
        "Quechua family": "familia quechua",
        "The following": "Las siguientes",
        "languages in the": "lenguas de la",
    },
    "pt": {
        # Full sentences
        "Slides are ordered chronologically by the earliest recording date in AILLA's holdings.":
            "Os slides estão ordenados cronologicamente pela data de gravação mais antiga no acervo do AILLA.",
        "As AILLA's collections grow, these languages may be featured in future updates to this map.":
            "À medida que as coleções do AILLA crescerem, essas línguas poderão ser incluídas em futuras atualizações deste mapa.",
        "in the Archive of the Indigenous Languages of Latin America (AILLA) at the University of Texas at Austin.":
            "no Arquivo das Línguas Indígenas da América Latina (AILLA) da Universidade do Texas em Austin.",
        "A chronological journey through the documentation of": "Uma jornada cronológica através da documentação de",
        # Title-slide headlines
        "Mayan Languages in the AILLA Archive": "Línguas maias no arquivo AILLA",
        "Quechua Languages in the AILLA Archive": "Línguas quéchuas no arquivo AILLA",
        # Multi-word phrases
        "Mayan languages": "as línguas maias",
        "Quechua languages": "as línguas quéchuas",
        "items in AILLA's current holdings.": "itens no acervo atual do AILLA.",
        "are listed in the closing summary.": "são listadas no resumo final.",
        "is listed in the closing summary.": "é listada no resumo final.",
        "with detailed slides": "com slides detalhados",
        "detailed slides": "slides detalhados",
        "This map features": "Este mapa apresenta",
        "have fewer than": "têm menos de",
        "An additional": "Além disso,",
        "Mayan family": "família maia",
        "Quechua family": "família quéchua",
        "The following": "As seguintes",
        "languages in the": "línguas da",
    },
}

# Regex-based replacements for short words that need word-boundary protection.
# Each entry is (pattern, replacement). Applied after template phrases.
REGEX_TRANSLATIONS = {
    "es": [
        # "N items" → "N elementos" (but not inside URLs or "items in AILLA's...")
        (r'(\d+) items\b', r'\1 elementos'),
        (r'(\d+) item\b', r'\1 elemento'),
        (r'(\d+) collections\b', r'\1 colecciones'),
        (r'(\d+) collection\b', r'\1 colección'),
        # "N languages" in <strong> tags
        (r'<strong>(\d+) languages</strong>', r'<strong>\1 lenguas</strong>'),
        # "N languages" outside <strong> tags (e.g. in summary text)
        (r'(\d+) languages\b', r'\1 lenguas'),
        # "covering REGION" in title slide
        (r'\bcovering\b', 'que cubren'),
    ],
    "pt": [
        (r'(\d+) items\b', r'\1 itens'),
        (r'(\d+) item\b', r'\1 item'),
        (r'(\d+) collections\b', r'\1 coleções'),
        (r'(\d+) collection\b', r'\1 coleção'),
        (r'<strong>(\d+) languages</strong>', r'<strong>\1 línguas</strong>'),
        (r'(\d+) languages\b', r'\1 línguas'),
        (r'\bcovering\b', 'cobrindo'),
    ],
}


class StoryMapTranslator:
    """Translates StoryMapJS JSON files using Google Cloud Translate API.

    Uses a two-tier approach:
    1. Curated lookup dicts for labels and template phrases (consistent, free)
    2. Google Cloud Translate API for free-text descriptions (staff-authored text)

    The API is only called for text that isn't covered by the lookup dicts,
    minimizing costs and ensuring consistent terminology.
    """

    def __init__(self, dry_run: bool = False):
        self.dry_run = dry_run
        self._client = None
        self._api_call_count = 0
        self._api_char_count = 0

    @property
    def client(self) -> translate.Client:
        """Lazy-initialize the translation client."""
        if self._client is None:
            if self.dry_run:
                return None
            self._client = translate.Client()
        return self._client

    def translate_text(self, text: str, target_lang: str) -> str:
        """Translate text using the Google Cloud Translate API.

        Args:
            text: Source text in English.
            target_lang: Target language code ('es' or 'pt').

        Returns:
            Translated text.
        """
        if not text or not text.strip():
            return text

        if self.dry_run:
            print(f"    [DRY RUN] Would translate ({target_lang}): {text[:80]}...")
            return text

        self._api_call_count += 1
        self._api_char_count += len(text)

        result = self.client.translate(text, target_language=target_lang, source_language="en")
        return result["translatedText"]

    def translate_html_content(self, html: str, target_lang: str) -> str:
        """Translate HTML content, preserving tags and non-translatable elements.

        Strategy:
        1. Replace known labels via lookup dict
        2. Extract free-text segments (descriptions) and translate via API
        3. Preserve URLs, ISO codes, numbers, and HTML structure

        Args:
            html: HTML string from a StoryMap slide.
            target_lang: Target language code.

        Returns:
            Translated HTML string.
        """
        if not html:
            return html

        result = html

        # Step 1: Replace known labels
        labels = LABEL_TRANSLATIONS.get(target_lang, {})
        for en_label, translated_label in labels.items():
            result = result.replace(en_label, translated_label)

        # Step 2: Replace known template phrases (longest first to avoid
        # partial matches)
        templates = TEMPLATE_TRANSLATIONS.get(target_lang, {})
        for en_phrase, translated_phrase in sorted(
            templates.items(), key=lambda x: len(x[0]), reverse=True
        ):
            result = result.replace(en_phrase, translated_phrase)

        # Step 3: Apply regex-based replacements for short words with
        # word-boundary protection (e.g., "N items" → "N elementos")
        regex_rules = REGEX_TRANSLATIONS.get(target_lang, [])
        for pattern, replacement in regex_rules:
            result = re.sub(pattern, replacement, result)

        # Step 4: Translate remaining free-text in <p> tags that aren't just
        # labels/metadata. We look for <p> content that doesn't start with
        # <em> (those are label lines) and isn't a link-only paragraph.
        result = self._translate_description_paragraphs(result, target_lang)

        return result

    def _translate_description_paragraphs(self, html: str, target_lang: str) -> str:
        """Find and translate free-text description paragraphs.

        Identifies <p> tags containing prose descriptions (not label lines,
        not link-only paragraphs) and translates them via the API.

        Args:
            html: HTML string, possibly with labels already translated.
            target_lang: Target language code.

        Returns:
            HTML with description paragraphs translated.
        """
        # Match <p> tags that contain plain text (descriptions from AILLA)
        # Skip: <p><em>...: (label lines), <p><a href (link-only), <p><strong> (counts)
        pattern = r'<p>(?!<em>|<a |<strong>)([^<]+(?:<[^>]+>[^<]*)*)</p>'

        def replace_match(match):
            inner = match.group(1).strip()
            # Skip if it's very short or just whitespace
            if len(inner) < 10:
                return match.group(0)
            # Skip if it's mostly numbers/codes
            if re.match(r'^[\d\-\s/]+$', inner):
                return match.group(0)
            translated = self.translate_text(inner, target_lang)
            return f"<p>{translated}</p>"

        return re.sub(pattern, replace_match, html)

    def translate_headline(self, headline: str, target_lang: str) -> str:
        """Translate a slide headline.

        Language names are preserved; only template text like title-slide
        headlines get translated via the lookup dict.

        Args:
            headline: Slide headline string.
            target_lang: Target language code.

        Returns:
            Translated headline.
        """
        templates = TEMPLATE_TRANSLATIONS.get(target_lang, {})
        labels = LABEL_TRANSLATIONS.get(target_lang, {})

        # Check if it's a known title-slide headline or label
        if headline in templates:
            return templates[headline]
        if headline in labels:
            return labels[headline]

        # For language slides, the headline is "Language Name (YYYY-YYYY)"
        # — these should NOT be translated (language names stay as-is)
        return headline

    def translate_slide(self, slide: dict[str, Any], target_lang: str) -> dict[str, Any]:
        """Translate a single StoryMap slide.

        Args:
            slide: StoryMapJS slide dict.
            target_lang: Target language code.

        Returns:
            Translated copy of the slide.
        """
        translated = copy.deepcopy(slide)

        if "text" in translated:
            text_obj = translated["text"]

            if "headline" in text_obj:
                text_obj["headline"] = self.translate_headline(
                    text_obj["headline"], target_lang
                )

            if "text" in text_obj:
                text_obj["text"] = self.translate_html_content(
                    text_obj["text"], target_lang
                )

        return translated

    def translate_storymap(self, data: dict[str, Any], target_lang: str) -> dict[str, Any]:
        """Translate a complete StoryMapJS JSON structure.

        Args:
            data: English StoryMapJS JSON dict.
            target_lang: Target language code ('es' or 'pt').

        Returns:
            Translated copy of the StoryMapJS structure.
        """
        translated = copy.deepcopy(data)

        # Update the language field
        translated["storymap"]["language"] = target_lang

        # Translate each slide
        slides = translated["storymap"]["slides"]
        for i, slide in enumerate(slides):
            slide_type = "title" if i == 0 else f"slide {i}"
            if self.dry_run:
                print(f"  Translating {slide_type}...")
            slides[i] = self.translate_slide(slide, target_lang)

        return translated

    def print_stats(self) -> None:
        """Print translation API usage statistics."""
        print(f"\nAPI usage: {self._api_call_count} calls, "
              f"{self._api_char_count:,} characters")


def generate_preview_html(storymap_data: dict[str, Any], title: str,
                          output_path: Path, lang_code: str) -> None:
    """Generate a self-contained HTML preview file for a translated StoryMap.

    Args:
        storymap_data: Complete StoryMapJS JSON structure.
        title: Title for the HTML page.
        output_path: Path to write the HTML file.
        lang_code: Language code for the HTML lang attribute.
    """
    json_str = json.dumps(storymap_data, ensure_ascii=False)
    html = f"""<!DOCTYPE html>
<html lang="{lang_code}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Preview: {title}</title>
    <link rel="stylesheet" href="https://cdn.knightlab.com/libs/storymapjs/latest/css/storymap.css">
    <style>body {{ margin: 0; padding: 0; }} #storymap {{ width: 100%; height: 100vh; }}</style>
</head>
<body>
    <div id="storymap"></div>
    <script src="https://cdn.knightlab.com/libs/storymapjs/latest/js/storymap-min.js"></script>
    <script>
        var storymap_data = {json_str};
        var storymap = new KLStoryMap.StoryMap("storymap", storymap_data, {{}});
        window.addEventListener("resize", function() {{ storymap.updateDisplay(); }});
    </script>
</body>
</html>"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"  Saved preview: {output_path}")


def main() -> None:
    """Translate StoryMap JSON files to Spanish and Portuguese."""
    parser = argparse.ArgumentParser(
        description="Translate StoryMapJS JSON files from English to Spanish/Portuguese."
    )
    parser.add_argument(
        "--family",
        choices=["mayan", "quechua"],
        help="Translate only this family (default: both)",
    )
    parser.add_argument(
        "--lang",
        choices=["es", "pt"],
        help="Translate to only this language (default: both)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be translated without making API calls",
    )
    args = parser.parse_args()

    data_dir = Path(__file__).parent.parent / "data"
    project_root = Path(__file__).parent.parent

    # Determine which families and languages to process
    families = [args.family] if args.family else list(SOURCE_FILES.keys())
    languages = [args.lang] if args.lang else list(TARGET_LANGUAGES.keys())

    translator = StoryMapTranslator(dry_run=args.dry_run)

    print("AILLA Language Atlas — StoryMap Translation Pipeline")
    print(f"Families: {', '.join(families)}")
    print(f"Target languages: {', '.join(f'{code} ({name})' for code, name in TARGET_LANGUAGES.items() if code in languages)}")
    if args.dry_run:
        print("MODE: Dry run (no API calls)\n")
    else:
        print()

    for family in families:
        source_path = data_dir / SOURCE_FILES[family]
        if not source_path.exists():
            print(f"ERROR: {source_path} not found. Run build_storymaps.py first.")
            continue

        with open(source_path, "r", encoding="utf-8") as f:
            source_data = json.load(f)

        slide_count = len(source_data["storymap"]["slides"])
        print(f"{'='*60}")
        print(f"Translating {family.title()} StoryMap ({slide_count} slides)")
        print(f"{'='*60}")

        for lang_code in languages:
            lang_name = TARGET_LANGUAGES[lang_code]
            print(f"\n→ {lang_name} ({lang_code})")

            translated = translator.translate_storymap(source_data, lang_code)

            # Write translated JSON
            output_filename = SOURCE_FILES[family].replace(".json", f"_{lang_code}.json")
            output_path = data_dir / output_filename
            with open(output_path, "w", encoding="utf-8") as f:
                json.dump(translated, f, indent=2, ensure_ascii=False)
            print(f"  Saved: {output_path}")

            # Write translated preview HTML
            title_headline = translated["storymap"]["slides"][0]["text"]["headline"]
            preview_filename = f"preview_{family}_{lang_code}.html"
            preview_path = project_root / preview_filename
            generate_preview_html(translated, title_headline, preview_path, lang_code)

    translator.print_stats()

    if not args.dry_run:
        print("\nDone. Output files:")
        for family in families:
            for lang_code in languages:
                output_filename = SOURCE_FILES[family].replace(".json", f"_{lang_code}.json")
                print(f"  data/{output_filename}")
                print(f"  preview_{family}_{lang_code}.html")


if __name__ == "__main__":
    main()
